### ISSUE TITLE
Add a refresh option on the WAC AKS-HCI dashboard

### ISSUE THREAD

**Issue by abhilashaagarwala** [Azure/aks-hybrid#103]
**Title**: Add a refresh option on the WAC AKS-HCI dashboard

**Description**: Add a refresh option on the WAC AKS-HCI dashboard

**Comment by priyasatheesh** [comment]
@Abhilasha - While WAC can add a refresh option in the dashboard, we will definitely need to understand what is causing this behaviour behind scenes. Could you probe the customer to get the repro steps that caused this sympthom?

**Comment by cmwendwa** [comment]
This can be closed, we have refresh options on the dashboard.
