### ISSUE TITLE
[BUG] Kubernetes version mismatch cause AKS Hybrid cluster deployment failure

### ISSUE THREAD

**Issue by HassanAlmanasrah** [Azure/aks-hybrid#268]
**Describe the bug**
When we run install-akshci, the Linux-K8s-1.23.8-v20220928 image version is downloaded automatically, which going to be used in K8S cluster deployments. https://learn.microsoft.com/en-us/azure/aks/hybrid/kubernetes-walkthrough-powershell

once the custom location and vnet are created, and we are deploying cluster from the Azure portal https://learn.microsoft.com/en-us/azure/aks/hybrid/create-aks-hybrid-preview-portal the Kubernetes version dropdown box is not changeable and hardcoded with version v1.21.9. adding this version 
 
![image](https://user-images.githubusercontent.com/54538594/197970480-22b97c0e-d9ab-4c34-9af4-4b69039abbfd.png)

at the end of https://learn.microsoft.com/en-us/azure/aks/hybrid/create-aks-hybrid-preview-networks?tabs=staticip%2Clinux-vhd#download-the-kubernetes-vhd-file we should add Kubernetes image, however the image seems doesn't exist with below error

VERBOSE: [10/26/2022 01:12:46] [Kva] Applying configuration
Unable to locate a image release with Version: 1.0.14.10929 OS: Linux K8sVersion: 1.21.9.
At C:\Program Files\WindowsPowerShell\Modules\Kva\1.0.36\Common.psm1:4259 char:5
+     throw $([System.String]::Format([System.Globalization.CultureInfo ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to locat...ersion: 1.21.9.:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to locate a image release with Version: 1.0.14.10929 OS: Linux K8sVersion: 1.21.9

any deployment for K8S cluster from Azure portal or CLI (define version 1.23.8) is not succeeded.
understand that we have known issue that only version can be deployed is 1.21.9 https://learn.microsoft.com/en-us/azure/aks/hybrid/troubleshoot-aks-hybrid-preview#the-infrastructure-administrator-didnt-download-the-kubernetes-vhd-image-using-add-kvagalleryimage , however we are unable to add this image to HCI using the command Add-KvaGalleryImage -kubernetesVersion 1.21.9

**To Reproduce**
1. install AKS on HCI
2. Install ARC Resource Bridge
3. create custom location and vnet 
4. Deploy K8S cluster from portal

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- AKS-HCI Version (i.e. Public Preview October-2020)
- Kubernetes Version (i.e. 1.18.8)

**Additional context**

**Collect log files**
- From a PowerShell Admin window run **Get-AksHciLogs**
- If you are running into issues with the deployment wizard in Windows Admin Center, run 
**Get-SMEUILogs.ps1** from the machine hosting Windows Admin Center.”

**Comment by JohnGageanu** [comment]
Can you please update the progress of this bug. It is still there. Thank you.

**Comment by HassanAlmanasrah** [comment]
managed to redeploy AKS with older version (August ) as per highlighted in known issues
https://learn.microsoft.com/en-us/azure/aks/hybrid/troubleshoot-aks-hybrid-preview#you-are-not-running-the-august-release-of-aks-host-management-cluster

and tested the deployment of cluster from Azure portal, which created control plan and Load balancer VMs only, and the workers were not created. I will do more testing and raise new issue for that . I think this issue can be closed. thanks.
