### ISSUE TITLE
Install-MOC - GetRelease error returned by API call - Received unexpected response code: 404

### ISSUE THREAD

**Issue by mahoncj** [Azure/aks-hybrid#276]
Reference issue: #194 and #202 

Module: AksHCI
Version: 1.1.49

Attempting to perform an AKS deployment on Azure Stack HCI and receiving the following error:

`Install-Moc failed.
Exception [GetRelease error returned by API call: Post
"https://msk8s.api.cdp.microsoft.com/api/v1.1/contents/default/namespaces/default/names/mocstack-stable/versions/1.0.15.11104/files?action=generateDownloadInfo&ForegroundPriority=True": POST
https://msk8s.api.cdp.microsoft.com/api/v1.1/contents/default/namespaces/default/names/mocstack-stable/versions/1.0.15.11104/files?action=generateDownloadInfo&ForegroundPriority=True giving up
after 6 attempt(s): Received unexpected response code: 404] `

MOC validation was successful via the `Set-AksHciConfig` cmdlet.

![image](https://user-images.githubusercontent.com/30126189/204971988-bbc10125-85d9-4da8-97c3-930a1483a342.png)

**To Reproduce**

1. Run Install-Akshci
2. See error

**Expected behavior**
- Successful downloads.

**Environment:**
OS: Azure Stack HCI (22H2) GA Release

**Comment by HassanAlmanasrah** [comment]
got the same issue for the URL , and tested two different versions for AKS.

**Comment by strickos9** [comment]
Getting the same error on different hosts, was working fine yesterday

**Comment by Elektronenvolt** [comment]
I've seen 404 responses as well at a cluster update in the last 36 to 48 hours. I've asked @baziwane about it Wednesday and he confirmed an outage on some files. I've started the update again a few hours ago, it works now - try again.

**Comment by mahoncj** [comment]
> I've seen 404 responses as well at a cluster update in the last 36 to 48 hours. I've asked @baziwane about it Wednesday and he confirmed an outage on some files. I've started the update again a few hours ago, it works now - try again, looks like it's fixed.

Thanks! Confirmed it is now working for me as well.
