### ISSUE TITLE
[BUG] Set-AksHciConfig Crashes After Two+ Hours

### ISSUE THREAD

**Issue by SantosVictorero** [Azure/aks-hybrid#354]
When running Set-AksHciConfig it runs for over two hours:

![image](https://github.com/Azure/aks-hybrid/assets/1824105/ec140722-6699-4342-a69d-70467469d4c2)

then it displays this error:

![image](https://github.com/Azure/aks-hybrid/assets/1824105/cf960bee-e189-4c58-9f9d-8054752474b6)

I have been using AksHci/AksHybrid for a while and never have seen this error.

**Expected behavior**
AksHci configuration.

**Environment (please complete the following information):**
- OS: Windows Server 2019 
- Memory 256 GB 
- Storage 4 TB

I also noticed that there are several errors related to FailoverClustering-Client in the System Logs:
LogExtendedErrorInformation (974): Extended RPC error information:
ProcessID is 2624
System time is: 55/473/7847 584:0:6176:32037
Generating component is 2
Status is 1753
Detection location is 501
Flags is 0
NumberOfParameters is 4
Unicode string: ncacn_ip_tcp
Unicode string: CBSI-AKSHCI-SRV
Long val: -1182943054
Long val: 382312662

It look like it was installed by Initialize-AksHciNode!? (I am just running one node)  
  
Get-AksHciLogs returns the following error:

![image](https://github.com/Azure/aks-hybrid/assets/1824105/d2457216-fdc5-4d80-afe3-e426890efe13)

**Comment by Elektronenvolt** [comment]
I've noticed that validation checks had been improved with the last release(s). They discovered an IP range issue at one of my setups.  In your setup, you can reach a VM 172.16.10.1 from your host? Any Firewall between host vlan and AKS Hybrid vlan? Meanwhile the validation checks create a VM and check connectivity, helps a lot avoid troubles after setup.
I see such error messages in test setups where I have no routing from the host IP to the configured IP ranges for AKS Hybrid nodepool.

**Comment by SantosVictorero** [comment]
Thanks for your comments @Elektronenvolt,

I did not check that since it was working fine in previous versions, with the same configuration. I will check if there are any new firewall ports that need to be open.

 :+1:

**Comment by SantosVictorero** [comment]
I found the problem, somehow the Virtual Switch of the Virtual Machine got corrupted. After I deleted and recreated the Virtual Switch, the installation proceeded successfully.
