### ISSUE TITLE
[BUG] Update-AksHciCluster -name <cluster> -kubernetesVersion <version> changes Windows OS version

### ISSUE THREAD

**Issue by Elektronenvolt** [Azure/aks-hybrid#359]
**Describe the bug**
After Updating the Kubernetes version of cluster node pools - Windows Server 2022 nodes are changed to 2019.

**To Reproduce**
Execute: `Update-AksHciCluster -name "cluster" -kubernetesVersion "version"` 

**Expected behavior**
Don't change the OS version.

**Screenshots**
![image](https://github.com/Azure/aks-hybrid/assets/6702311/6a9a57a2-f929-4637-b2c5-9777c0ee02da)

**Environment (please complete the following information):**
- AKS-HCI Version (1.0.21.11030)
- Kubernetes Version (1.24.11)

**Additional context**
I've seen this issue already with the previous August release, but was not sure if somebody changed the node OS on purpose. For this release I used a separate test cluster where I tested the updates.

**Collect log files**
- From a PowerShell Admin window run **Get-AksHciLogs**
- If you are running into issues with the deployment wizard in Windows Admin Center, run 
**Get-SMEUILogs.ps1** from the machine hosting Windows Admin Center.”

**Comment by cm3cmf** [comment]
Same here. I can confirm that it is a Bug.
If you have installed 2022 initially, it brakes the Update. It will look for the not existing 2019 image and the Update gets stuck.

After a couple of hours it will timeout the update. We had to create a new nodepool :(

Has this been testet before publishing the release?

**Comment by Elektronenvolt** [comment]
It never broke the update in our case, just changed the OS image from WS 2022 to 2019 with the update.

And, I've noticed it the first time with the previous release (August), but I was not sure if a bug or somebody changed the nodepool on purpose. With the October release I've tested for this on dedicated test cluster where only I have access to.

**Comment by mkostersitz** [comment]
Hello @Elektronenvolt, we are in the process of pushing a new PowerShell Version with the fix for this issue. Thank you for reporting it. We are also adding additional validation to our pipelines to ensure we will not miss similar issues in the future.

**Comment by cm3cmf** [comment]
> Hello @Elektronenvolt, we are in the process of pushing a new PowerShell Version with the fix for this issue. Thank you for reporting it. We are also adding additional validation to our pipelines to ensure we will not miss similar issues in the future.

Does that mean it is fixed now?
Update the PS Module?
