### ISSUE TITLE
[BUG] AKS installation stuck on "Validate KVA"

### ISSUE THREAD

**Issue by arp-mbender** [Azure/aks-hybrid#363]
**Describe the bug**
When attempting to install Azure Kubernetes Service via Windows Admin Center on a Windows Server 2022 the process seems to be stuck at the "Validate KVA" validation step on the "Review and Validation" phase of the process. Since the process never finishes it is also impossible to download logs.

**To Reproduce**
1. Proceed with the basic AKS setup from Windows Admin Center, using a new VM with Server 2022 Standard Core as the target.
2. Using DHCP for the network assignment with no VLAN; i.e. simplest setup possible
3. Get stuck during validation

**Expected behavior**
Validation finishes in a reasonable time **or** throws an error in case something is wrong.

**Screenshots**
Validation still ongoing after 10 minutes (where everything else completed in 30 seconds or so):
![Zrzut ekranu 2023-11-19 131356](https://github.com/Azure/aks-hybrid/assets/60735180/ea92990c-e88f-4148-ba04-fa9f7b7ef8e4)
I can wait even longer, but the result will be the same.

**Environment (please complete the following information):**
- OS: Both Admin Center and target is running Windows Server 2022 Standard Core
- Brave browser (but I also tried Chrome and Edge)
- Admin Center Version 2306

**Comment by markamber** [comment]
I can reproduce this! On server 2019 clustered and 2022 standalone. 

Looks like a bootstrap VM boots and gets its cloud config but then nothing happens. I was using static addresses , no VLAN, and static addresses yes VLAN. 

Seems like it might just be broken

**Comment by arp-mbender** [comment]
Quite annoying, TBH. I keep trying to get some experience with Kubernetes by setting up a basic environment, and I keep hitting strange roadblocks. Processes that should automate this... don't work (like the one described here), while manual attempts at setting things up fail due to versioning issues between some tutorial and my own environment...

**Comment by abhilashaagarwala** [comment]
@SummerSmith @walterov FYI

**Comment by arp-mbender** [comment]
Aye, it turned out to be a connectivity issue. I'm not sure how I missed it. :(

**Comment by Elektronenvolt** [comment]
@arp-mbender in our case it was a network card not supporting SR-IOV, Virtual Machine Queues, e.g. Replaced it now with a "Hyper-V certified" card.

**Comment by arp-mbender** [comment]
@Elektronenvolt I had the EXACT same issue. Well, SR-IOV was supported, but it doesn't support MAC address spoofing (but there are no errors enabling this; it just doesn't work in the end).
