### ISSUE TITLE
New-AksHciCluster should have a max-pods parameter

### ISSUE THREAD

**Issue by infbase** [Azure/aks-hybrid#90]
**Title**:
New-AksHciCluster should have a max-pods parameter

**Description**:
When creating a cluster, there should be the possibility to change the default max pods per node value of 110, like in the az aks create command.

**Comment by msjingli** [comment]
Thanks for the feedback. We will take care of it in our backlog.

**Comment by scooley** [comment]
Completed but forgot to close :).
